---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gnlist-prototype-pv
  labels:
    name: gnlist-prototype-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/gnlist-prototype
