apiVersion: v1
kind: Secret
metadata:
  name: gnlist
type: Opaque
data:
  # user: gnuser
  db.user: Z251c2Vy
  # password: gnpassword
  db.password: Z25wYXNzd29yZA==
  # password: gnpassword
  root.password: Z25wyxnzd29yza==
  session.secret: c2vzc2lvbnnly3jldA==
