web:
  build: .
  volumes:
    - .:/app
  ports:
    - "4567:4567"
  env_file:
    - "config/env.sh"
  links:
    - db
  command: "/app/app.rb -o 0.0.0.0"
db:
  image: gnames/mariadb:10.0
  ports:
    - "13306:3306"
  environment:
    - MDB_ADMIN_PASSWORD=test
