version: "2"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8080:8080"
    env_file:
      - "config/env.sh"
    links:
      - db
  db:
    image: gnames/mariadb:10.0
    ports:
      - "0.0.0.0:13306:3306"
    environment:
      - MDB_ADMIN_PASSWORD=admin
    volumes:
      - mariadb:/var/lib/mysql
volumes:
  mariadb:
    external: false
