---
apiVersion: v1
kind: Service
metadata:
  name: gnlist-prototype
  labels:
    app: gnlist-prototype
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9292
  selector:
    app: gnlist-prototype
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnlist-prototype
spec:
  replicas: 1
  template:
    metadata:
      name: gnlist-prototype
      labels:
        app: gnlist-prototype
        tier: frontend
    spec:
      containers:
        - name: gnlist-prototype
          image: gnames/listresolver:2017-07-05-1
          livenessProbe:
            httpGet:
              path: /
              port: 9292
            initialDelaySeconds: 60
            timeoutSeconds: 3
          args:
            - /app/exe/production.sh
          env:
            - name: CODECLIMATE_REPO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gnlist-prototype
                  key: session.secret
            - name: RACKAPP_DB_HOST
              value: gnlist-prototype-db
            - name: RACKAPP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gnlist-prototype
                  key: db.user
            - name: RACKAPP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gnlist-prototype
                  key: db.user.password
            - name: RACKAPP_RESOLVER_URL_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: gnlist-prototype
                  key: resolver.url
            - name: RACKAPP_RESOLVER_URL_SERVER
              valueFrom:
                configMapKeyRef:
                  name: gnlist-prototype
                  key: resolver.internal.url
            - name: RACKAPP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: gnlist-prototype
                  key: server
            - name: RACKAPP_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: gnlist-prototype
                  key: session.secret
            - name: RACKAPP_PUMA_WORKERS
              valueFrom:
                configMapKeyRef:
                  name: gnlist-prototype
                  key: puma.workers
            - name: RACKAPP_ASYC_WORKERS
              valueFrom:
                configMapKeyRef:
                  name: gnlist-prototype
                  key: async.workers
            - name: RACKAPP_DATA_SOURCES
              valueFrom:
                configMapKeyRef:
                  name: gnlist-prototype
                  key: data.sources
            - name: RACK_ENV
              valueFrom:
                configMapKeyRef:
                  name: gnlist-prototype
                  key: env
          ports:
            - containerPort: 9292
              name: http
