apiVersion: v1
kind: Service
metadata:
  name: gnlist-prototype-db
  labels:
    app: gnlist-prototype
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: gnlist-prototype
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnlist-prototype-db
spec:
  replicas: 1
  template:
    metadata:
      name: gnlist-prototype
      labels:
        app: gnlist-prototype
        tier: backend
    spec:
      volumes:
        - name: gnlist-prototype-vol
          persistentVolumeClaim:
            claimName: gnlist-prototype-pvc
      containers:
        - name: gnlist-prototype-db
          image: gnames/postgres-solo
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gnlist-prototype
                  key: root.password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gnlist-prototype
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gnlist-prototype
                  key: db.user.password
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: gnlist-prototype
                  key: db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: psql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: gnlist-prototype-vol
