---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gnbulk-pv
  labels:
    name: gnbulk-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/gnbulk
