apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gnbulk-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: gnbulk-pv


