session_secret: <%= ENV["RACKAPP_SESSION_SECRET"] %>
database:
  common: &common
    adapter: mysql2
    encoding: utf8
    reconnect: true
    host: <%= ENV["RACKAPP_DB_HOST"] %>
    username: <%= ENV["RACKAPP_DB_USERNAME"] %>
    password: <%= ENV["RACKAPP_DB_PASSWORD"] %>

  development:
    <<: *common
    database: checklist_dev

  test:
    <<: *common
    database: checklist_test

  production:
    <<: *common
    database: checklist
