RACK_ENV=development
RACKAPP_UNICORN_WORKERS=1
RACKAPP_SESSION_SECRET=changeme
RACKAPP_SERVER=0.0.0.0:9292
RACKAPP_DB_HOST=db
RACKAPP_DB_USERNAME=postgres
RACKAPP_DB_PASSWORD=""
CODECLIMATE_REPO_TOKEN=""
